### ISSUE TITLE
path: 2-1/Nesneye Yonelik Programlama/slaytlar/2021/slaytlar  Otomatik Print İşlemi

### ISSUE THREAD

**Issue by fbera231** [baselkelziye/YTU_Bilgisayar_Muhendisligi_Arsiv#30]
Pathini yazdığım dosyaları indirdim ama her açtığımda print ekranı geliyor adobe js disable yaptığımda da fotoğraf ve yazılar iç içe giriyor düzeltmesi güzel olur. Adobe dışında bir platform kullanınca böyle bir sıkıntı çıkmadı.

**Comment by kaayra2000** [comment]
şu an düzelttiğimi düşünüyorum kontrol etme imkanın var mı (önce tüm dosyaları .ogd'ye çevirdim sonra .pdf'e çevirdim)

**Comment by fbera231** [comment]
Evet şimdi normal açılıyor teşekkürler
